project:
  type: book
  output-dir: docs

engine: knitr
filters:
  - webr

date: "last-modified"
date-format: iso
institute: "Wilfrid Laurier University"
number-depth: 2
author: "Dr. Devan Becker"
execute:
    warning: false

book:
  title: "ST230 Supplement"
  subtitle: "Devan found shiny things and wants to use them"
  author: "Dr. Devan Becker"
  date: "last-modified"
  page-footer:
    left: |
      Copyright Devan Becker, released under Creative Commons Attribution-ShareAlike 4.0.
  page-navigation: true
  sidebar: 
    title: "Probs and Stats"
    background: light
    style: docked
    border: true
  chapters:
    - index.qmd
    - part: Pre-Midterm
      chapters:
        - 01-combinations_in_R.qmd
        - 02-Probability.qmd
        - 03-Distributions.qmd
        - 04-Normal.qmd
        - 05-Plots_Numbers.qmd
    - part: Post-Midterm
      chapters:
        - 06-CLT-Example.qmd
        - 07-t-tests.qmd
        - 08-two-t-tests.qmd
        - 09-props.qmd
  appendices:
    - a1-playground.qmd
    - a2-t-tester.qmd
    - a3-t-table.qmd

format:
  html:
    theme:
      light: [flatly, tweaks.scss]
      dark: [darkly, tweaks.scss]
    code-fold: true
    code-summary: "Show the code"
    embed-resources: false
